# Shoplifting Detection

Computer vision project for detecting shoplifting activity from video data.

In [1]:
import cv2
import os

video_path = r"C:\Users\ZUHAIR\Shoplifting project\normal.mp4"  # change path
output_folder = r"C:\Users\ZUHAIR\Shoplifting project\normal frames"  # change path

os.makedirs(output_folder, exist_ok=True)

# Open the input video.
cap = cv2.VideoCapture(video_path)

frame_count = 0

while True:
    ret, frame = cap.read()

    if not ret:
        break

    frame_name = os.path.join(
        output_folder,
        f"frame_{frame_count:05d}.jpg"
    )

    cv2.imwrite(frame_name, frame)

    frame_count += 1

cap.release()

print(f"Total Frames Saved: {frame_count}")

Total Frames Saved: 2131

In [2]:
import cv2
import os

video_path = r"C:\Users\ZUHAIR\Shoplifting project\suspecious.mp4"  # change path
output_folder = r"C:\Users\ZUHAIR\Shoplifting project\suspecious frames"  # change path

os.makedirs(output_folder, exist_ok=True)

# Open the input video.
cap = cv2.VideoCapture(video_path)

frame_count = 0

while True:
    ret, frame = cap.read()

    if not ret:
        break

    frame_name = os.path.join(
        output_folder,
        f"frame_{frame_count:05d}.jpg"
    )

    cv2.imwrite(frame_name, frame)

    frame_count += 1

cap.release()

print(f"Total Frames Saved: {frame_count}")

Total Frames Saved: 800

In [4]:
from ultralytics import YOLO

# Load the YOLO model.
model = YOLO("yolo11x.pt")

results = model(r"C:\Users\ZUHAIR\Shoplifting project\normal frames\frame_00001.jpg")

results[0].show()

image 1/1 C:\Users\ZUHAIR\Shoplifting project\normal frames\frame_00001.jpg: 480x640 1 person, 2 bottles, 146.0ms
Speed: 5.9ms preprocess, 146.0ms inference, 29.1ms postprocess per image at shape (1, 3, 480, 640)

In [5]:
for box in results[0].boxes:
    print("Class:", int(box.cls[0]))
    print("Confidence:", float(box.conf[0]))
    print("Coordinates:", box.xyxy[0].tolist())
    print("-"*30)

Class: 0
Confidence: 0.7679834365844727
Coordinates: [215.17715454101562, 96.89861297607422, 286.7327880859375, 337.9671630859375]
------------------------------
Class: 39
Confidence: 0.25343799591064453
Coordinates: [668.4854125976562, 463.0975341796875, 685.3446044921875, 506.0869445800781]
------------------------------
Class: 39
Confidence: 0.25324100255966187
Coordinates: [699.123779296875, 502.94122314453125, 724.2548828125, 544.1834716796875]
------------------------------

In [7]:
import cv2

image = cv2.imread(r"C:\Users\ZUHAIR\Shoplifting project\normal frames\frame_00001.jpg")

for box in results[0].boxes:

    if int(box.cls[0]) == 0:   # person only

        x1, y1, x2, y2 = map(int, box.xyxy[0])

        person_crop = image[y1:y2, x1:x2]

        cv2.imwrite("person_crop.jpg", person_crop)

        print("Person cropped and saved")

Person cropped and saved

In [8]:
import os
import cv2
from ultralytics import YOLO

# Load YOLO model
# Load the YOLO model.
model = YOLO("yolo11x.pt")

# Input frames folder
input_folder = r"C:\Users\ZUHAIR\Shoplifting project\normal frames"

# Output cropped persons folder
output_folder = r"C:\Users\ZUHAIR\Shoplifting project\normal person"

os.makedirs(output_folder, exist_ok=True)

count = 0

for file in os.listdir(input_folder):

    if file.endswith(".jpg"):

        image_path = os.path.join(input_folder, file)

        image = cv2.imread(image_path)

        results = model(image)

        for box in results[0].boxes:

            # Person class only
            if int(box.cls[0]) == 0:

                x1, y1, x2, y2 = map(int, box.xyxy[0])

                person_crop = image[y1:y2, x1:x2]

                save_path = os.path.join(
                    output_folder,
                    f"person_{count:05d}.jpg"
                )

                cv2.imwrite(save_path, person_crop)

                count += 1

print(f"Saved {count} person crops")

0: 480x640 1 person, 2 bottles, 49.5ms
Speed: 12.3ms preprocess, 49.5ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 2 bottles, 51.0ms
Speed: 3.0ms preprocess, 51.0ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 2 bottles, 49.1ms
Speed: 2.8ms preprocess, 49.1ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 2 bottles, 45.6ms
Speed: 2.0ms preprocess, 45.6ms inference, 4.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 2 bottles, 50.2ms
Speed: 2.0ms preprocess, 50.2ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 2 bottles, 45.4ms
Speed: 2.0ms preprocess, 45.4ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 2 bottles, 46.6ms
Speed: 3.6ms preprocess, 46.6ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 46.6ms
Speed: 2.3ms preprocess, 46.6ms inference, 4.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 51.0ms
Speed: 2.5ms preprocess, 51.0ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 50.7ms
Speed: 2.2ms preprocess, 50.7ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 44.3ms
Speed: 2.7ms preprocess, 44.3ms inference, 3.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 45.7ms
Speed: 3.2ms preprocess, 45.7ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 48.8ms
Speed: 3.1ms preprocess, 48.8ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 45.0ms
Speed: 2.0ms preprocess, 45.0ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 51.4ms
Speed: 4.0ms preprocess, 51.4ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 62.5ms
Speed: 2.3ms preprocess, 62.5ms inference, 5.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 69.6ms
Speed: 4.2ms preprocess, 69.6ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 60.0ms
Speed: 3.2ms preprocess, 60.0ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 2 bottles, 63.8ms
Speed: 4.1ms preprocess, 63.8ms inference, 3.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 2 bottles, 88.8ms
Speed: 3.4ms preprocess, 88.8ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 2 bottles, 52.0ms
Speed: 4.3ms preprocess, 52.0ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 microwave, 53.0ms
Speed: 3.3ms preprocess, 53.0ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 73.7ms
Speed: 3.3ms preprocess, 73.7ms inference, 5.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 61.7ms
Speed: 4.0ms preprocess, 61.7ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 53.0ms
Speed: 3.2ms preprocess, 53.0ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 48.5ms
Speed: 3.7ms preprocess, 48.5ms inference, 4.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 47.6ms
Speed: 3.9ms preprocess, 47.6ms inference, 4.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 62.6ms
Speed: 3.3ms preprocess, 62.6ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 47.8ms
Speed: 3.5ms preprocess, 47.8ms inference, 4.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 48.5ms
Speed: 2.8ms preprocess, 48.5ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 54.3ms
Speed: 2.5ms preprocess, 54.3ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 54.3ms
Speed: 3.8ms preprocess, 54.3ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 49.7ms
Speed: 3.5ms preprocess, 49.7ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 46.8ms
Speed: 3.0ms preprocess, 46.8ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 48.8ms
Speed: 2.8ms preprocess, 48.8ms inference, 3.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 47.5ms
Speed: 3.2ms preprocess, 47.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 46.8ms
Speed: 2.7ms preprocess, 46.8ms inference, 3.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 53.0ms
Speed: 4.1ms preprocess, 53.0ms inference, 3.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 48.1ms
Speed: 3.4ms preprocess, 48.1ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 46.5ms
Speed: 4.1ms preprocess, 46.5ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 50.2ms
Speed: 3.3ms preprocess, 50.2ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 48.0ms
Speed: 3.0ms preprocess, 48.0ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 48.3ms
Speed: 2.9ms preprocess, 48.3ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 46.5ms
Speed: 2.8ms preprocess, 46.5ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 48.7ms
Speed: 3.8ms preprocess, 48.7ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 47.0ms
Speed: 3.6ms preprocess, 47.0ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 47.0ms
Speed: 2.7ms preprocess, 47.0ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 47.3ms
Speed: 3.4ms preprocess, 47.3ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 49.2ms
Speed: 4.5ms preprocess, 49.2ms inference, 4.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 54.0ms
Speed: 3.9ms preprocess, 54.0ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 microwave, 47.1ms
Speed: 4.0ms preprocess, 47.1ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 55.4ms
Speed: 2.6ms preprocess, 55.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 46.6ms
Speed: 2.9ms preprocess, 46.6ms inference, 3.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 47.7ms
Speed: 3.0ms preprocess, 47.7ms inference, 6.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 49.3ms
Speed: 2.8ms preprocess, 49.3ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 45.4ms
Speed: 3.7ms preprocess, 45.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 49.1ms
Speed: 4.5ms preprocess, 49.1ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 46.7ms
Speed: 3.5ms preprocess, 46.7ms inference, 3.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 48.8ms
Speed: 3.4ms preprocess, 48.8ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 64.6ms
Speed: 3.3ms preprocess, 64.6ms inference, 3.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 50.7ms
Speed: 2.5ms preprocess, 50.7ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 46.4ms
Speed: 2.7ms preprocess, 46.4ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 47.2ms
Speed: 3.7ms preprocess, 47.2ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 48.6ms
Speed: 2.7ms preprocess, 48.6ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 48.4ms
Speed: 2.7ms preprocess, 48.4ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 48.3ms
Speed: 2.6ms preprocess, 48.3ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 48.7ms
Speed: 3.4ms preprocess, 48.7ms inference, 3.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 46.8ms
Speed: 2.9ms preprocess, 46.8ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 47.2ms
Speed: 2.8ms preprocess, 47.2ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 48.5ms
Speed: 3.0ms preprocess, 48.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 49.2ms
Speed: 3.5ms preprocess, 49.2ms inference, 3.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 50.7ms
Speed: 2.9ms preprocess, 50.7ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 49.1ms
Speed: 3.9ms preprocess, 49.1ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 50.4ms
Speed: 3.4ms preprocess, 50.4ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 47.9ms
Speed: 2.8ms preprocess, 47.9ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 48.2ms
Speed: 4.2ms preprocess, 48.2ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 55.0ms
Speed: 3.1ms preprocess, 55.0ms inference, 4.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 56.4ms
Speed: 3.5ms preprocess, 56.4ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 49.4ms
Speed: 2.8ms preprocess, 49.4ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 47.4ms
Speed: 2.5ms preprocess, 47.4ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 51.4ms
Speed: 4.3ms preprocess, 51.4ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 48.1ms
Speed: 2.6ms preprocess, 48.1ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 48.3ms
Speed: 2.8ms preprocess, 48.3ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 62.0ms
Speed: 4.3ms preprocess, 62.0ms inference, 5.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 1 refrigerator, 71.5ms
Speed: 3.2ms preprocess, 71.5ms inference, 5.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 46.7ms
Speed: 3.0ms preprocess, 46.7ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 47.6ms
Speed: 2.5ms preprocess, 47.6ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 45.1ms
Speed: 2.2ms preprocess, 45.1ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 1 refrigerator, 46.1ms
Speed: 2.2ms preprocess, 46.1ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 1 refrigerator, 45.5ms
Speed: 2.4ms preprocess, 45.5ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 47.5ms
Speed: 3.8ms preprocess, 47.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 58.4ms
Speed: 3.7ms preprocess, 58.4ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 microwave, 1 refrigerator, 47.3ms
Speed: 2.3ms preprocess, 47.3ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 48.4ms
Speed: 3.9ms preprocess, 48.4ms inference, 3.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 45.4ms
Speed: 2.2ms preprocess, 45.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 48.8ms
Speed: 2.9ms preprocess, 48.8ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 46.1ms
Speed: 3.0ms preprocess, 46.1ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 45.5ms
Speed: 3.0ms preprocess, 45.5ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 46.9ms
Speed: 2.9ms preprocess, 46.9ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 46.2ms
Speed: 3.2ms preprocess, 46.2ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 47.1ms
Speed: 3.3ms preprocess, 47.1ms inference, 4.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 47.3ms
Speed: 2.6ms preprocess, 47.3ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 50.2ms
Speed: 3.7ms preprocess, 50.2ms inference, 3.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 45.9ms
Speed: 3.7ms preprocess, 45.9ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 50.5ms
Speed: 3.4ms preprocess, 50.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 47.2ms
Speed: 3.5ms preprocess, 47.2ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 58.4ms
Speed: 3.5ms preprocess, 58.4ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 75.9ms
Speed: 3.8ms preprocess, 75.9ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 57.0ms
Speed: 2.5ms preprocess, 57.0ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 78.7ms
Speed: 3.1ms preprocess, 78.7ms inference, 6.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 48.5ms
Speed: 4.6ms preprocess, 48.5ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 51.2ms
Speed: 2.9ms preprocess, 51.2ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 51.7ms
Speed: 3.5ms preprocess, 51.7ms inference, 5.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 57.7ms
Speed: 3.9ms preprocess, 57.7ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 45.5ms
Speed: 2.7ms preprocess, 45.5ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 46.0ms
Speed: 2.2ms preprocess, 46.0ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 45.8ms
Speed: 2.5ms preprocess, 45.8ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 53.4ms
Speed: 4.4ms preprocess, 53.4ms inference, 6.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 75.9ms
Speed: 3.6ms preprocess, 75.9ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 45.9ms
Speed: 2.3ms preprocess, 45.9ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 56.7ms
Speed: 2.5ms preprocess, 56.7ms inference, 3.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 74.8ms
Speed: 4.0ms preprocess, 74.8ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 47.3ms
Speed: 3.0ms preprocess, 47.3ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 1 microwave, 1 refrigerator, 46.7ms
Speed: 2.8ms preprocess, 46.7ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 1 microwave, 1 refrigerator, 47.3ms
Speed: 2.4ms preprocess, 47.3ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 1 microwave, 1 refrigerator, 45.8ms
Speed: 3.4ms preprocess, 45.8ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 48.6ms
Speed: 2.3ms preprocess, 48.6ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 1 microwave, 1 refrigerator, 46.2ms
Speed: 2.9ms preprocess, 46.2ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 1 microwave, 1 refrigerator, 46.1ms
Speed: 3.5ms preprocess, 46.1ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dining table, 1 microwave, 1 refrigerator, 75.8ms
Speed: 3.3ms preprocess, 75.8ms inference, 4.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 1 microwave, 1 refrigerator, 72.2ms
Speed: 3.1ms preprocess, 72.2ms inference, 3.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 bottle, 1 dining table, 1 microwave, 1 refrigerator, 46.1ms
Speed: 2.5ms preprocess, 46.1ms inference, 2.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 refrigerator, 66.7ms
Speed: 3.0ms preprocess, 66.7ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 refrigerator, 52.9ms

In [9]:
import os
import cv2
from ultralytics import YOLO

# Load YOLO model
# Load the YOLO model.
model = YOLO("yolo11x.pt")

# Input frames folder
input_folder = r"C:\Users\ZUHAIR\Shoplifting project\suspecious frames"

# Output cropped persons folder
output_folder = r"C:\Users\ZUHAIR\Shoplifting project\shoplifting person"

os.makedirs(output_folder, exist_ok=True)

count = 0

for file in os.listdir(input_folder):

    if file.endswith(".jpg"):

        image_path = os.path.join(input_folder, file)

        image = cv2.imread(image_path)

        results = model(image)

        for box in results[0].boxes:

            # Person class only
            if int(box.cls[0]) == 0:

                x1, y1, x2, y2 = map(int, box.xyxy[0])

                person_crop = image[y1:y2, x1:x2]

                save_path = os.path.join(
                    output_folder,
                    f"person_{count:05d}.jpg"
                )

                cv2.imwrite(save_path, person_crop)

                count += 1

print(f"Saved {count} person crops")

0: 480x640 1 dog, 1 chair, 1 dining table, 1 microwave, 49.6ms
Speed: 17.5ms preprocess, 49.6ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 dog, 1 chair, 1 dining table, 1 microwave, 49.9ms
Speed: 2.8ms preprocess, 49.9ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 dog, 1 chair, 1 microwave, 1 clock, 47.3ms
Speed: 2.8ms preprocess, 47.3ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 dog, 1 chair, 1 microwave, 1 clock, 47.5ms
Speed: 3.2ms preprocess, 47.5ms inference, 1.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 dog, 1 chair, 1 microwave, 1 clock, 44.8ms
Speed: 2.6ms preprocess, 44.8ms inference, 3.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 dog, 1 chair, 1 microwave, 1 clock, 45.8ms
Speed: 2.2ms preprocess, 45.8ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 chair, 1 microwave, 1 clock, 46.8ms
Speed: 3.3ms preprocess, 46.8ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 dog, 1 chair, 1 microwave, 1 clock, 45.4ms
Speed: 2.4ms preprocess, 45.4ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dog, 1 chair, 1 dining table, 1 microwave, 1 clock, 45.8ms
Speed: 2.1ms preprocess, 45.8ms inference, 3.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 dog, 1 chair, 1 dining table, 1 microwave, 1 clock, 45.6ms
Speed: 2.4ms preprocess, 45.6ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 dining table, 1 microwave, 1 clock, 47.4ms
Speed: 2.1ms preprocess, 47.4ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 dining table, 1 microwave, 1 clock, 45.7ms
Speed: 2.2ms preprocess, 45.7ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 dining table, 1 microwave, 1 clock, 45.3ms
Speed: 2.9ms preprocess, 45.3ms inference, 3.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 2 persons, 1 chair, 1 dining table, 1 microwave, 1 clock, 45.3ms
Speed: 2.2ms preprocess, 45.3ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 dining table, 1 microwave, 1 clock, 46.2ms
Speed: 2.9ms preprocess, 46.2ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 dining table, 1 microwave, 1 clock, 45.8ms
Speed: 2.9ms preprocess, 45.8ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 dining table, 1 microwave, 1 clock, 44.7ms
Speed: 3.4ms preprocess, 44.7ms inference, 6.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 dining table, 1 microwave, 47.1ms
Speed: 2.4ms preprocess, 47.1ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.0ms
Speed: 2.1ms preprocess, 47.0ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.9ms
Speed: 2.6ms preprocess, 46.9ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.7ms
Speed: 2.5ms preprocess, 46.7ms inference, 3.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 44.7ms
Speed: 2.2ms preprocess, 44.7ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 51.8ms
Speed: 2.3ms preprocess, 51.8ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 48.9ms
Speed: 3.7ms preprocess, 48.9ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 48.1ms
Speed: 2.2ms preprocess, 48.1ms inference, 4.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 52.3ms
Speed: 2.5ms preprocess, 52.3ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 48.5ms
Speed: 3.9ms preprocess, 48.5ms inference, 4.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.5ms
Speed: 2.2ms preprocess, 46.5ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.4ms
Speed: 2.6ms preprocess, 46.4ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.4ms
Speed: 4.5ms preprocess, 47.4ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 44.9ms
Speed: 2.5ms preprocess, 44.9ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.4ms
Speed: 2.2ms preprocess, 45.4ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.8ms
Speed: 2.5ms preprocess, 45.8ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.4ms
Speed: 3.1ms preprocess, 47.4ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 46.2ms
Speed: 2.9ms preprocess, 46.2ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 59.1ms
Speed: 3.1ms preprocess, 59.1ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 46.9ms
Speed: 2.6ms preprocess, 46.9ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 44.7ms
Speed: 2.1ms preprocess, 44.7ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 46.1ms
Speed: 2.2ms preprocess, 46.1ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 45.3ms
Speed: 2.1ms preprocess, 45.3ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 47.4ms
Speed: 2.7ms preprocess, 47.4ms inference, 5.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 45.8ms
Speed: 2.0ms preprocess, 45.8ms inference, 3.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 48.3ms
Speed: 2.3ms preprocess, 48.3ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 48.7ms
Speed: 3.4ms preprocess, 48.7ms inference, 3.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 50.7ms
Speed: 2.3ms preprocess, 50.7ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 52.1ms
Speed: 2.2ms preprocess, 52.1ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 45.9ms
Speed: 2.8ms preprocess, 45.9ms inference, 4.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 47.3ms
Speed: 2.1ms preprocess, 47.3ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 45.5ms
Speed: 2.3ms preprocess, 45.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 46.1ms
Speed: 2.1ms preprocess, 46.1ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 45.4ms
Speed: 2.6ms preprocess, 45.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 46.8ms
Speed: 2.3ms preprocess, 46.8ms inference, 3.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 45.5ms
Speed: 2.2ms preprocess, 45.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 46.2ms
Speed: 2.1ms preprocess, 46.2ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 47.4ms
Speed: 3.8ms preprocess, 47.4ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 57.2ms
Speed: 2.6ms preprocess, 57.2ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 47.4ms
Speed: 2.2ms preprocess, 47.4ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 45.7ms
Speed: 2.7ms preprocess, 45.7ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 44.2ms
Speed: 2.2ms preprocess, 44.2ms inference, 3.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 45.6ms
Speed: 2.2ms preprocess, 45.6ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.7ms
Speed: 2.3ms preprocess, 45.7ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 1 refrigerator, 45.4ms
Speed: 3.3ms preprocess, 45.4ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.5ms
Speed: 2.5ms preprocess, 45.5ms inference, 3.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.3ms
Speed: 2.6ms preprocess, 46.3ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 54.2ms
Speed: 2.2ms preprocess, 54.2ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.7ms
Speed: 2.6ms preprocess, 45.7ms inference, 4.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 51.1ms
Speed: 2.1ms preprocess, 51.1ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 48.8ms
Speed: 1.8ms preprocess, 48.8ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.4ms
Speed: 3.7ms preprocess, 45.4ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 44.3ms
Speed: 2.1ms preprocess, 44.3ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.4ms
Speed: 2.2ms preprocess, 45.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.1ms
Speed: 2.2ms preprocess, 46.1ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.2ms
Speed: 3.4ms preprocess, 46.2ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 44.1ms
Speed: 2.2ms preprocess, 44.1ms inference, 4.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.0ms
Speed: 2.1ms preprocess, 47.0ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.7ms
Speed: 2.1ms preprocess, 45.7ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.2ms
Speed: 2.2ms preprocess, 46.2ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.0ms
Speed: 2.6ms preprocess, 46.0ms inference, 3.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 48.1ms
Speed: 3.0ms preprocess, 48.1ms inference, 2.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.0ms
Speed: 3.2ms preprocess, 46.0ms inference, 1.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.6ms
Speed: 3.4ms preprocess, 45.6ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.2ms
Speed: 2.1ms preprocess, 45.2ms inference, 3.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.4ms
Speed: 2.2ms preprocess, 47.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.0ms
Speed: 2.2ms preprocess, 47.0ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.9ms
Speed: 3.4ms preprocess, 45.9ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.8ms
Speed: 2.8ms preprocess, 46.8ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.0ms
Speed: 2.1ms preprocess, 46.0ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.8ms
Speed: 2.2ms preprocess, 45.8ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.5ms
Speed: 3.5ms preprocess, 45.5ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.8ms
Speed: 2.8ms preprocess, 45.8ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 49.7ms
Speed: 2.9ms preprocess, 49.7ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.7ms
Speed: 4.0ms preprocess, 47.7ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.6ms
Speed: 2.3ms preprocess, 45.6ms inference, 4.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.6ms
Speed: 2.1ms preprocess, 45.6ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.2ms
Speed: 2.3ms preprocess, 45.2ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.0ms
Speed: 2.1ms preprocess, 46.0ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.8ms
Speed: 2.9ms preprocess, 45.8ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.6ms
Speed: 2.3ms preprocess, 45.6ms inference, 3.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 48.0ms
Speed: 2.0ms preprocess, 48.0ms inference, 2.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 52.6ms
Speed: 2.5ms preprocess, 52.6ms inference, 3.8ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.2ms
Speed: 2.2ms preprocess, 46.2ms inference, 3.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.3ms
Speed: 2.4ms preprocess, 46.3ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 48.3ms
Speed: 3.1ms preprocess, 48.3ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.7ms
Speed: 3.0ms preprocess, 47.7ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.8ms
Speed: 2.1ms preprocess, 47.8ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.8ms
Speed: 2.2ms preprocess, 45.8ms inference, 6.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 44.3ms
Speed: 3.1ms preprocess, 44.3ms inference, 3.7ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.3ms
Speed: 2.0ms preprocess, 45.3ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.4ms
Speed: 2.1ms preprocess, 46.4ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.5ms
Speed: 2.4ms preprocess, 47.5ms inference, 3.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.3ms
Speed: 3.6ms preprocess, 45.3ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 53.8ms
Speed: 3.1ms preprocess, 53.8ms inference, 2.6ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.0ms
Speed: 2.9ms preprocess, 47.0ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.0ms
Speed: 2.7ms preprocess, 45.0ms inference, 3.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.6ms
Speed: 2.7ms preprocess, 45.6ms inference, 2.5ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.5ms
Speed: 2.6ms preprocess, 47.5ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 48.1ms
Speed: 2.8ms preprocess, 48.1ms inference, 3.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.5ms
Speed: 2.8ms preprocess, 47.5ms inference, 3.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.5ms
Speed: 2.0ms preprocess, 45.5ms inference, 2.1ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 48.6ms
Speed: 2.1ms preprocess, 48.6ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.6ms
Speed: 2.9ms preprocess, 45.6ms inference, 2.4ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.7ms
Speed: 3.5ms preprocess, 45.7ms inference, 4.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.9ms
Speed: 3.6ms preprocess, 45.9ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.9ms
Speed: 2.7ms preprocess, 46.9ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.6ms
Speed: 2.8ms preprocess, 45.6ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 46.5ms
Speed: 2.9ms preprocess, 46.5ms inference, 3.9ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.5ms
Speed: 2.2ms preprocess, 45.5ms inference, 2.3ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.6ms
Speed: 2.8ms preprocess, 45.6ms inference, 2.0ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 47.2ms
Speed: 3.9ms preprocess, 47.2ms inference, 2.2ms postprocess per image at shape (1, 3, 480, 640)

0: 480x640 1 person, 1 chair, 1 microwave, 45.4ms
Speed: 1.9ms preprocess, 45.4ms inference, 3.8ms postprocess per image at shape (1, 3, 480, 640)


In [1]:
from ultralytics import YOLO
# Load the YOLO model.
pose_model = YOLO("yolo11x-pose.pt")
results = pose_model(r"C:\Users\ZUHAIR\Shoplifting project\normal person\person_00000.jpg")
results[0].show()

image 1/1 C:\Users\ZUHAIR\Shoplifting project\normal person\person_00000.jpg: 640x192 1 person, 154.9ms
Speed: 6.9ms preprocess, 154.9ms inference, 28.5ms postprocess per image at shape (1, 3, 640, 192)

In [2]:
print(results[0].keypoints)

ultralytics.engine.results.Keypoints object with attributes:

conf: tensor([[0.8584, 0.9031, 0.1904, 0.9714, 0.0480, 0.9900, 0.9634, 0.9394, 0.6092, 0.9310, 0.5819, 0.9883, 0.9795, 0.9974, 0.9943, 0.9894, 0.9863]], device='cuda:0')
data: tensor([[[1.8277e+01, 3.0190e+01, 8.5837e-01],
         [1.9586e+01, 2.5605e+01, 9.0307e-01],
         [1.7862e+01, 2.6474e+01, 1.9041e-01],
         [2.8814e+01, 2.1638e+01, 9.7143e-01],
         [2.6328e+01, 2.3821e+01, 4.7953e-02],
         [4.0714e+01, 4.1786e+01, 9.9000e-01],
         [3.3443e+01, 4.1896e+01, 9.6344e-01],
         [3.7882e+01, 7.8857e+01, 9.3936e-01],
         [2.8583e+01, 7.4497e+01, 6.0922e-01],
         [2.3811e+01, 1.0396e+02, 9.3096e-01],
         [1.4118e+01, 8.7514e+01, 5.8186e-01],
         [3.7943e+01, 1.0776e+02, 9.8830e-01],
         [3.4394e+01, 1.0523e+02, 9.7951e-01],
         [3.5778e+01, 1.5968e+02, 9.9737e-01],
         [3.9120e+01, 1.5236e+02, 9.9426e-01],
         [4.2158e+01, 2.1385e+02, 9.8942e-01],
         [5.3033e+01, 1.9485e+02, 9.8626e-01]]], device='cuda:0')
has_visible: True
orig_shape: (242, 66)
shape: torch.Size([1, 17, 3])
xy: tensor([[[ 18.2774,  30.1899],
         [ 19.5863,  25.6053],
         [ 17.8617,  26.4736],
         [ 28.8140,  21.6380],
         [ 26.3284,  23.8206],
         [ 40.7138,  41.7856],
         [ 33.4432,  41.8955],
         [ 37.8816,  78.8573],
         [ 28.5834,  74.4971],
         [ 23.8110, 103.9608],
         [ 14.1185,  87.5141],
         [ 37.9425, 107.7560],
         [ 34.3936, 105.2291],
         [ 35.7779, 159.6826],
         [ 39.1203, 152.3609],
         [ 42.1582, 213.8476],
         [ 53.0333, 194.8476]]], device='cuda:0')
xyn: tensor([[[0.2769, 0.1248],
         [0.2968, 0.1058],
         [0.2706, 0.1094],
         [0.4366, 0.0894],
         [0.3989, 0.0984],
         [0.6169, 0.1727],
         [0.5067, 0.1731],
         [0.5740, 0.3259],
         [0.4331, 0.3078],
         [0.3608, 0.4296],
         [0.2139, 0.3616],
         [0.5749, 0.4453],
         [0.5211, 0.4348],
         [0.5421, 0.6598],
         [0.5927, 0.6296],
         [0.6388, 0.8837],
         [0.8035, 0.8052]]], device='cuda:0')

In [5]:
print(results[0].keypoints.xy)

tensor([[[ 18.2774,  30.1899],
         [ 19.5863,  25.6053],
         [ 17.8617,  26.4736],
         [ 28.8140,  21.6380],
         [ 26.3284,  23.8206],
         [ 40.7138,  41.7856],
         [ 33.4432,  41.8955],
         [ 37.8816,  78.8573],
         [ 28.5834,  74.4971],
         [ 23.8110, 103.9608],
         [ 14.1185,  87.5141],
         [ 37.9425, 107.7560],
         [ 34.3936, 105.2291],
         [ 35.7779, 159.6826],
         [ 39.1203, 152.3609],
         [ 42.1582, 213.8476],
         [ 53.0333, 194.8476]]], device='cuda:0')

In [6]:
print(results[0].keypoints.xyn.shape)
print(results[0].keypoints.xyn)

torch.Size([1, 17, 2])
tensor([[[0.2769, 0.1248],
         [0.2968, 0.1058],
         [0.2706, 0.1094],
         [0.4366, 0.0894],
         [0.3989, 0.0984],
         [0.6169, 0.1727],
         [0.5067, 0.1731],
         [0.5740, 0.3259],
         [0.4331, 0.3078],
         [0.3608, 0.4296],
         [0.2139, 0.3616],
         [0.5749, 0.4453],
         [0.5211, 0.4348],
         [0.5421, 0.6598],
         [0.5927, 0.6296],
         [0.6388, 0.8837],
         [0.8035, 0.8052]]], device='cuda:0')

In [7]:
kpts = results[0].keypoints.xyn[0]
print(kpts.shape)
flat = kpts.cpu().numpy().flatten()
print(flat.shape)
print(flat)

torch.Size([17, 2])
(34,)
[    0.27693     0.12475     0.29676     0.10581     0.27063      0.1094     0.43658    0.089413     0.39892    0.098432     0.61688     0.17267     0.50672     0.17312     0.57396     0.32586     0.43308     0.30784     0.36077     0.42959     0.21392     0.36163     0.57489     0.44527     0.52112     0.43483
     0.54209     0.65985     0.59273     0.62959     0.63876     0.88367     0.80353     0.80516]

In [8]:
image_path = r"C:\Users\ZUHAIR\Shoplifting project\normal person\person_00000.jpg"

results = pose_model(image_path)

kpts = results[0].keypoints.xyn[0]

flat = kpts.cpu().numpy().flatten()

row = list(flat)

row.append(0)

print(len(row))
print(row[:10])

image 1/1 C:\Users\ZUHAIR\Shoplifting project\normal person\person_00000.jpg: 640x192 1 person, 70.5ms
Speed: 1.3ms preprocess, 70.5ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 192)
35
[np.float32(0.27693), np.float32(0.12475157), np.float32(0.29676282), np.float32(0.10580711), np.float32(0.2706324), np.float32(0.109395124), np.float32(0.4365756), np.float32(0.08941331), np.float32(0.3989152), np.float32(0.09843239)]

In [9]:
import os
import pandas as pd
from ultralytics import YOLO

# Load pose model
# Load the YOLO model.
pose_model = YOLO("yolo11x-pose.pt")

# Folder containing cropped persons
input_folder = r"C:\Users\ZUHAIR\Shoplifting project\normal person"

# Store all rows here
all_rows = []

columns = [
    "nose_x", "nose_y",
    "left_eye_x", "left_eye_y",
    "right_eye_x", "right_eye_y",
    "left_ear_x", "left_ear_y",
    "right_ear_x", "right_ear_y",
    "left_shoulder_x", "left_shoulder_y",
    "right_shoulder_x", "right_shoulder_y",
    "left_elbow_x", "left_elbow_y",
    "right_elbow_x", "right_elbow_y",
    "left_wrist_x", "left_wrist_y",
    "right_wrist_x", "right_wrist_y",
    "left_hip_x", "left_hip_y",
    "right_hip_x", "right_hip_y",
    "left_knee_x", "left_knee_y",
    "right_knee_x", "right_knee_y",
    "left_ankle_x", "left_ankle_y",
    "right_ankle_x", "right_ankle_y",
    "label"
]

for file in os.listdir(input_folder):

    if file.endswith(".jpg"):

        image_path = os.path.join(input_folder, file)

        results = pose_model(image_path, verbose=False)

        # Skip failed detections
        if results[0].keypoints is None:
            continue

        try:
            kpts = results[0].keypoints.xyn[0]

            flat = kpts.cpu().numpy().flatten()

            row = list(flat)

            row.append(0)   # Normal label

            all_rows.append(row)

        except:
            continue

df = pd.DataFrame(all_rows, columns=columns)

df.to_csv("normal_keypoints.csv", index=False)

print("Rows saved:", len(df))

Rows saved: 2131

In [10]:
df.head(10)

,nose_x,nose_y,left_eye_x,left_eye_y,right_eye_x,right_eye_y,left_ear_x,left_ear_y,right_ear_x,right_ear_y,...,right_hip_y,left_knee_x,left_knee_y,right_knee_x,right_knee_y,left_ankle_x,left_ankle_y,right_ankle_x,right_ankle_y,label
0,0.276930,0.124752,0.296763,0.105807,0.270632,0.109395,0.436576,0.089413,0.398915,0.098432,...,0.434831,0.542089,0.659846,0.592731,0.629591,0.638761,0.883668,0.803535,0.805155,0
1,0.337384,0.119349,0.365185,0.099426,0.317657,0.104583,0.503391,0.084242,0.395483,0.096469,...,0.444896,0.581702,0.666166,0.641588,0.638980,0.685445,0.874896,0.840527,0.804952,0
2,0.337549,0.119346,0.365334,0.099447,0.317781,0.104583,0.503573,0.084237,0.395589,0.096431,...,0.443871,0.580025,0.664807,0.638101,0.636566,0.686654,0.873979,0.838917,0.802286,0
3,0.339796,0.115513,0.361050,0.096224,0.328004,0.099729,0.484672,0.080842,0.422846,0.089556,...,0.450940,0.586279,0.692837,0.656690,0.646223,0.681887,0.908292,0.852670,0.819289,0
4,0.310359,0.127041,0.329242,0.104509,0.289242,0.109255,0.465929,0.080085,0.378910,0.093179,...,0.453054,0.553726,0.692003,0.612615,0.637875,0.671987,0.890842,0.812968,0.808838,0
5,0.302023,0.113161,0.324444,0.092333,0.286203,0.096507,0.458411,0.077485,0.380408,0.088185,...,0.447930,0.562693,0.681199,0.600523,0.639919,0.704526,0.887115,0.849197,0.811378,0
6,0.293756,0.126455,0.295882,0.104962,0.283798,0.110779,0.409867,0.085217,0.431142,0.100151,...,0.445100,0.560180,0.669118,0.625202,0.635480,0.734473,0.873447,0.817627,0.802017,0
7,0.296085,0.129461,0.294797,0.106989,0.288502,0.111156,0.404005,0.083170,0.449893,0.094643,...,0.444167,0.565842,0.676734,0.615573,0.644202,0.757582,0.900231,0.833306,0.837911,0
8,0.296121,0.129285,0.294889,0.106812,0.288781,0.110829,0.403774,0.083200,0.450876,0.094262,...,0.443809,0.566952,0.677036,0.615330,0.643640,0.758590,0.900711,0.833179,0.837353,0
9,0.259703,0.129443,0.259820,0.107687,0.257695,0.110083,0.383293,0.083083,0.452203,0.089844,...,0.437250,0.545664,0.684644,0.589177,0.656560,0.739887,0.901232,0.805688,0.855535,0

In [11]:
import os
import pandas as pd
from ultralytics import YOLO

# Load pose model
# Load the YOLO model.
pose_model = YOLO("yolo11x-pose.pt")

# Folder containing cropped persons
input_folder = r"C:\Users\ZUHAIR\Shoplifting project\shoplifting person"

# Store all rows here
all_rows = []

columns = [
    "nose_x", "nose_y",
    "left_eye_x", "left_eye_y",
    "right_eye_x", "right_eye_y",
    "left_ear_x", "left_ear_y",
    "right_ear_x", "right_ear_y",
    "left_shoulder_x", "left_shoulder_y",
    "right_shoulder_x", "right_shoulder_y",
    "left_elbow_x", "left_elbow_y",
    "right_elbow_x", "right_elbow_y",
    "left_wrist_x", "left_wrist_y",
    "right_wrist_x", "right_wrist_y",
    "left_hip_x", "left_hip_y",
    "right_hip_x", "right_hip_y",
    "left_knee_x", "left_knee_y",
    "right_knee_x", "right_knee_y",
    "left_ankle_x", "left_ankle_y",
    "right_ankle_x", "right_ankle_y",
    "label"
]

for file in os.listdir(input_folder):

    if file.endswith(".jpg"):

        image_path = os.path.join(input_folder, file)

        results = pose_model(image_path, verbose=False)

        # Skip failed detections
        if results[0].keypoints is None:
            continue

        try:
            kpts = results[0].keypoints.xyn[0]

            flat = kpts.cpu().numpy().flatten()

            row = list(flat)

            row.append(1)   # Normal label

            all_rows.append(row)

        except:
            continue

df = pd.DataFrame(all_rows, columns=columns)

df.to_csv("shoplifting_keypoints.csv", index=False)

print("Rows saved:", len(df))

Rows saved: 726

In [12]:
df.head()

,nose_x,nose_y,left_eye_x,left_eye_y,right_eye_x,right_eye_y,left_ear_x,left_ear_y,right_ear_x,right_ear_y,...,right_hip_y,left_knee_x,left_knee_y,right_knee_x,right_knee_y,left_ankle_x,left_ankle_y,right_ankle_x,right_ankle_y,label
0,0.917339,0.133134,0.908724,0.114620,0.906915,0.116311,0.744605,0.100233,0.785657,0.106695,...,0.463124,0.491516,0.659567,0.407507,0.681582,0.353392,0.857750,0.172616,0.897843,1
1,0.912693,0.134302,0.900731,0.115412,0.904971,0.117424,0.728351,0.099771,0.788491,0.107740,...,0.464706,0.481242,0.661739,0.408991,0.681933,0.343049,0.859142,0.176387,0.898046,1
2,0.910291,0.121987,0.912598,0.106315,0.908133,0.105174,0.732385,0.097622,0.801208,0.097692,...,0.459273,0.458494,0.646631,0.431383,0.664700,0.315371,0.863090,0.190524,0.889098,1
3,0.938350,0.115975,0.920155,0.101092,0.919564,0.102894,0.739988,0.100328,0.804161,0.108781,...,0.451232,0.500209,0.656040,0.478903,0.657047,0.351098,0.895506,0.218816,0.903509,1
4,0.927949,0.127748,0.922545,0.113592,0.915015,0.112991,0.729015,0.111946,0.773000,0.114030,...,0.445167,0.570240,0.624149,0.465892,0.634643,0.481905,0.856113,0.227205,0.890079,1

In [13]:
import pandas as pd

normal_df = pd.read_csv("normal_keypoints.csv")
shoplifting_df = pd.read_csv("shoplifting_keypoints.csv")

print(normal_df.shape)
print(shoplifting_df.shape)

(2131, 35)
(726, 35)

In [14]:
dataset = pd.concat([normal_df,shoplifting_df],ignore_index=True)

In [15]:
dataset["label"].value_counts()

label
0    2131
1     726
Name: count, dtype: int64

In [16]:
dataset = pd.concat(
    [normal_df, shoplifting_df],
    ignore_index=True
)

print(dataset.shape)

print(dataset["label"].value_counts())

(2857, 35)
label
0    2131
1     726
Name: count, dtype: int64

In [17]:
X = dataset.drop("label",axis=1)
y = dataset["label"]
print(X.shape)
print(y.shape)

(2857, 34)
(2857,)

In [18]:
from sklearn.model_selection import train_test_split

# Split the data into training and test sets.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(2285, 34)
(572, 34)
(2285,)
(572,)

In [19]:
X_train = X_train.values
X_test = X_test.values

y_train = y_train.values
y_test = y_test.values

In [20]:
import torch
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)

y_train = torch.tensor(y_train, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

In [21]:
print(X_train.shape)

print(y_train.shape)

print(X_test.shape)

print(y_test.shape)

torch.Size([2285, 34])
torch.Size([2285])
torch.Size([572, 34])
torch.Size([572])

In [22]:
import torch.nn as nn
class ShopliftingNet(nn.Module):

    def __init__(self):
        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(34, 64),
            nn.ReLU(),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 1)

        )

    def forward(self, x):
        return self.network(x)

In [23]:
model = ShopliftingNet()

print(model)

ShopliftingNet(
  (network): Sequential(
    (0): Linear(in_features=34, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=32, bias=True)
    (3): ReLU()
    (4): Linear(in_features=32, out_features=1, bias=True)
  )
)

In [24]:
print(y_train.shape)
print(y_test.shape)

torch.Size([2285])
torch.Size([572])

In [25]:
y_train = y_train.unsqueeze(1)
y_test = y_test.unsqueeze(1)

In [26]:
criterion = nn.BCEWithLogitsLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

In [27]:
epochs = 50

for epoch in range(epochs):

    outputs = model(X_train)

    loss = criterion(outputs, y_train)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    if epoch % 5 == 0:
        print(
            f"Epoch {epoch}, Loss: {loss.item():.4f}"
        )

Epoch 0, Loss: 0.7475
Epoch 5, Loss: 0.7205
Epoch 10, Loss: 0.6983
Epoch 15, Loss: 0.6775
Epoch 20, Loss: 0.6559
Epoch 25, Loss: 0.6334
Epoch 30, Loss: 0.6106
Epoch 35, Loss: 0.5896
Epoch 40, Loss: 0.5734
Epoch 45, Loss: 0.5649

In [28]:
with torch.no_grad():
    outputs = model(X_test)

    predictions = torch.sigmoid(outputs)
    predictions = (predictions > 0.5).float()

In [29]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, predictions))
# Evaluate classification performance.
print(classification_report(y_test, predictions))

Accuracy: 0.7465034965034965
              precision    recall  f1-score   support

         0.0       0.75      1.00      0.85       427
         1.0       0.00      0.00      0.00       145

    accuracy                           0.75       572
   macro avg       0.37      0.50      0.43       572
weighted avg       0.56      0.75      0.64       572

C:\Users\ZUHAIR\miniconda3\envs\pytorch_gpu\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ZUHAIR\miniconda3\envs\pytorch_gpu\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ZUHAIR\miniconda3\envs\pytorch_gpu\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [30]:
pos_weight = torch.tensor([2131/726])

criterion = nn.BCEWithLogitsLoss(
    pos_weight=pos_weight
)

In [56]:
import torch
import torch.nn as nn

class ShopliftingNet(nn.Module):

    def __init__(self):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(34, 64),
            nn.ReLU(),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.network(x)

model = ShopliftingNet()

In [46]:
pos_weight = torch.tensor([2131 / 726], dtype=torch.float32)

criterion = nn.BCEWithLogitsLoss(
    pos_weight=pos_weight
)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

In [47]:
print(y_train.shape)
print(y_test.shape)

if len(y_train.shape) == 1:
    y_train = y_train.unsqueeze(1)

if len(y_test.shape) == 1:
    y_test = y_test.unsqueeze(1)

print(y_train.shape)
print(y_test.shape)

torch.Size([2285, 1])
torch.Size([572, 1])
torch.Size([2285, 1])
torch.Size([572, 1])

In [48]:
epochs = 300

for epoch in range(epochs):

    outputs = model(X_train)

    loss = criterion(outputs, y_train)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 1.0370
Epoch 10, Loss: 1.0283
Epoch 20, Loss: 1.0219
Epoch 30, Loss: 1.0127
Epoch 40, Loss: 1.0000
Epoch 50, Loss: 0.9828
Epoch 60, Loss: 0.9608
Epoch 70, Loss: 0.9328
Epoch 80, Loss: 0.8979
Epoch 90, Loss: 0.8536
Epoch 100, Loss: 0.8000
Epoch 110, Loss: 0.7399
Epoch 120, Loss: 0.6776
Epoch 130, Loss: 0.6174
Epoch 140, Loss: 0.5622
Epoch 150, Loss: 0.5140
Epoch 160, Loss: 0.4728
Epoch 170, Loss: 0.4372
Epoch 180, Loss: 0.4053
Epoch 190, Loss: 0.3779
Epoch 200, Loss: 0.3547
Epoch 210, Loss: 0.3347
Epoch 220, Loss: 0.3173
Epoch 230, Loss: 0.3015
Epoch 240, Loss: 0.2871
Epoch 250, Loss: 0.2741
Epoch 260, Loss: 0.2618
Epoch 270, Loss: 0.2512
Epoch 280, Loss: 0.2415
Epoch 290, Loss: 0.2323

In [49]:
with torch.no_grad():

    outputs = model(X_test)

    probabilities = torch.sigmoid(outputs)

    predictions = (probabilities > 0.5).float()

In [50]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:",
      accuracy_score(
          y_test.cpu(),
          predictions.cpu()
      ))

print("\nClassification Report:\n")

print(
# Evaluate classification performance.
    classification_report(
        y_test.cpu(),
        predictions.cpu()
    )
)

print("\nConfusion Matrix:\n")

print(
# Inspect the confusion matrix.
    confusion_matrix(
        y_test.cpu(),
        predictions.cpu()
    )
)

Accuracy: 0.9545454545454546

Classification Report:

              precision    recall  f1-score   support

         0.0       0.99      0.95      0.97       427
         1.0       0.87      0.97      0.92       145

    accuracy                           0.95       572
   macro avg       0.93      0.96      0.94       572
weighted avg       0.96      0.95      0.96       572


Confusion Matrix:

[[405  22]
 [  4 141]]

In [51]:
with torch.no_grad():

    train_outputs = model(X_train)

    train_probs = torch.sigmoid(train_outputs)

    train_preds = (train_probs > 0.5).float()

from sklearn.metrics import accuracy_score

print(
    "Train Accuracy:",
    accuracy_score(
        y_train.cpu(),
        train_preds.cpu()
    )
)

Train Accuracy: 0.9422319474835886

In [52]:
torch.save(model.state_dict(),"shoplifting_model.pth")

In [53]:
class ShopliftingNet(nn.Module):
    ...

In [55]:
print(model)

ShopliftingNet()

In [57]:
model = ShopliftingNet()

checkpoint = torch.load("shoplifting_model.pth")

print(checkpoint.keys())

odict_keys(['network.0.weight', 'network.0.bias', 'network.2.weight', 'network.2.bias', 'network.4.weight', 'network.4.bias'])

In [58]:
model.load_state_dict(
    torch.load("shoplifting_model.pth")
)

model.eval()

print("Loaded Successfully")

Loaded Successfully

In [1]:
import cv2
import os
import torch
import torch.nn as nn
import numpy as np
from ultralytics import YOLO

# =====================================
# YOUR TRAINED NEURAL NETWORK
# =====================================

class ShopliftingNet(nn.Module):

    def __init__(self):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(34, 64),
            nn.ReLU(),

            nn.Linear(64, 32),
            nn.ReLU(),

            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.network(x)


# =====================================
# LOAD TRAINED MODEL
# =====================================

model = ShopliftingNet()

model.load_state_dict(
    torch.load("shoplifting_model.pth")
)

model.eval()

print("Classifier Loaded")


# =====================================
# LOAD YOLO MODELS
# =====================================

# Load the YOLO model.
person_model = YOLO("yolo11x.pt")

# Load the YOLO model.
pose_model = YOLO("yolo11x-pose.pt")

print("YOLO Models Loaded")


# =====================================
# VIDEO PATH
# =====================================

video_path = r"D:\Project AI Shoplifting risk score\data\Videos_MERL_Shopping_Dataset\Videos_MERL_Shopping_Dataset\18_3_crop.mp4"

# Open the input video.
cap = cv2.VideoCapture(video_path)

# =====================================
# OUTPUT VIDEO
# =====================================

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)

fourcc = cv2.VideoWriter_fourcc(*'mp4v')

# Prepare the output video writer.
out = cv2.VideoWriter(
    "shoplifting_output4.mp4",
    fourcc,
    fps,
    (width, height)
)

print("Processing Video...")


# =====================================
# MAIN LOOP
# =====================================

while True:

    ret, frame = cap.read()

    if not ret:
        break

    det_results = person_model(
        frame,
        verbose=False
    )

    for box in det_results[0].boxes:

        cls = int(box.cls[0])

        # PERSON ONLY
        if cls != 0:
            continue

        x1, y1, x2, y2 = map(
            int,
            box.xyxy[0]
        )

        person_crop = frame[
            y1:y2,
            x1:x2
        ]

        if person_crop.size == 0:
            continue

        try:

            pose_results = pose_model(
                person_crop,
                verbose=False
            )

            if pose_results[0].keypoints is None:
                continue

            kpts = pose_results[0].keypoints.xyn[0]

            features = (
                kpts
                .cpu()
                .numpy()
                .flatten()
            )

            if len(features) != 34:
                continue

            features = torch.tensor(
                features,
                dtype=torch.float32
            ).unsqueeze(0)

            with torch.no_grad():

                output = model(features)

                probability = torch.sigmoid(
                    output
                ).item()

            # =====================================
            # LABEL
            # =====================================

            if probability > 0.5:

                label = "SHOPLIFTING"

                color = (0, 0, 255)

            else:

                label = "NORMAL"

                color = (0, 255, 0)

            # DEBUG PRINT
            print(label, round(probability, 3))

            # =====================================
            # DRAW
            # =====================================

            cv2.rectangle(
                frame,
                (x1, y1),
                (x2, y2),
                color,
                2
            )

            cv2.putText(
                frame,
                f"{label} {probability:.2f}",
                (x1, y1 - 10),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.7,
                color,
                2
            )

        except:
            continue

    out.write(frame)

# =====================================
# FINISH
# =====================================

cap.release()
out.release()

print("Video Saved Successfully")
print("Output File: shoplifting_output.mp4")

Classifier Loaded
YOLO Models Loaded
Processing Video...
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.992
SHOPLIFTING 0.988
SHOPLIFTING 0.94
SHOPLIFTING 0.954
SHOPLIFTING 0.996
SHOPLIFTING 0.969
SHOPLIFTING 0.996
SHOPLIFTING 0.978
SHOPLIFTING 0.922
SHOPLIFTING 0.814
SHOPLIFTING 0.993
SHOPLIFTING 0.999
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.979
SHOPLIFTING 0.66
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 0.992
SHOPLIFTING 0.996
SHOPLIFTING 0.923
SHOPLIFTING 1.0
SHOPLIFTING 0.602
SHOPLIFTING 0.505
SHOPLIFTING 0.899
SHOPLIFTING 0.772
SHOPLIFTING 0.978
SHOPLIFTING 0.977
SHOPLIFTING 0.938
SHOPLIFTING 0.922
SHOPLIFTING 0.947
SHOPLIFTING 0.931
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
NORMAL 0.114
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
NORMAL 0.149
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.97
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 0.996
SHOPLIFTING 1.0
SHOPLIFTING 0.997
NORMAL 0.275
SHOPLIFTING 0.554
SHOPLIFTING 0.999
NORMAL 0.166
SHOPLIFTING 0.564
NORMAL 0.391
NORMAL 0.382
SHOPLIFTING 0.611
SHOPLIFTING 0.955
NORMAL 0.387
SHOPLIFTING 0.978
SHOPLIFTING 0.969
SHOPLIFTING 0.992
SHOPLIFTING 0.989
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 0.999
SHOPLIFTING 0.92
SHOPLIFTING 0.999
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 0.999
SHOPLIFTING 0.999
SHOPLIFTING 0.998
SHOPLIFTING 0.996
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.998
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.996
SHOPLIFTING 1.0
SHOPLIFTING 0.995
SHOPLIFTING 1.0
SHOPLIFTING 0.993
SHOPLIFTING 1.0
SHOPLIFTING 0.998
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.998
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
NORMAL 0.262
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
NORMAL 0.161
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 0.998
NORMAL 0.22
SHOPLIFTING 0.996
SHOPLIFTING 0.993
SHOPLIFTING 1.0
SHOPLIFTING 0.977
SHOPLIFTING 1.0
SHOPLIFTING 0.806
SHOPLIFTING 0.863
NORMAL 0.143
SHOPLIFTING 0.734
NORMAL 0.296
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.995
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.519
SHOPLIFTING 0.927
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.834
SHOPLIFTING 0.872
SHOPLIFTING 0.897
SHOPLIFTING 0.971
SHOPLIFTING 0.948
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.935
SHOPLIFTING 0.982
SHOPLIFTING 0.94
SHOPLIFTING 0.932
SHOPLIFTING 0.998
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 0.995
SHOPLIFTING 0.998
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.934
SHOPLIFTING 0.859
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
NORMAL 0.108
SHOPLIFTING 1.0
SHOPLIFTING 1.0
NORMAL 0.067
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.992
SHOPLIFTING 0.987
SHOPLIFTING 0.998
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.996
SHOPLIFTING 0.988
SHOPLIFTING 0.716
SHOPLIFTING 0.997
SHOPLIFTING 0.934
SHOPLIFTING 0.861
SHOPLIFTING 0.985
SHOPLIFTING 0.734
SHOPLIFTING 0.997
SHOPLIFTING 0.997
SHOPLIFTING 0.977
SHOPLIFTING 0.958
SHOPLIFTING 0.998
SHOPLIFTING 0.999
SHOPLIFTING 0.999
SHOPLIFTING 0.99
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.997
SHOPLIFTING 0.974
SHOPLIFTING 0.989
SHOPLIFTING 0.987
SHOPLIFTING 0.999
SHOPLIFTING 0.932
SHOPLIFTING 0.788
SHOPLIFTING 0.521
SHOPLIFTING 0.918
SHOPLIFTING 0.97
SHOPLIFTING 0.992
SHOPLIFTING 0.998
SHOPLIFTING 1.0
SHOPLIFTING 0.58
SHOPLIFTING 0.994
SHOPLIFTING 0.552
NORMAL 0.234
NORMAL 0.277
NORMAL 0.32
SHOPLIFTING 0.973
SHOPLIFTING 0.825
SHOPLIFTING 0.661
SHOPLIFTING 0.956
SHOPLIFTING 0.827
SHOPLIFTING 0.789
SHOPLIFTING 0.953
SHOPLIFTING 0.944
SHOPLIFTING 0.951
SHOPLIFTING 0.806
SHOPLIFTING 0.933
SHOPLIFTING 0.788
SHOPLIFTING 0.967
SHOPLIFTING 0.915
SHOPLIFTING 0.674
SHOPLIFTING 0.699
SHOPLIFTING 0.751
SHOPLIFTING 0.612
SHOPLIFTING 0.69
SHOPLIFTING 0.928
SHOPLIFTING 0.989
SHOPLIFTING 0.964
SHOPLIFTING 0.992
SHOPLIFTING 0.969
SHOPLIFTING 0.982
SHOPLIFTING 0.991
SHOPLIFTING 0.968
SHOPLIFTING 0.893
SHOPLIFTING 0.787
SHOPLIFTING 0.675
SHOPLIFTING 0.892
SHOPLIFTING 0.93
SHOPLIFTING 0.77
SHOPLIFTING 0.79
SHOPLIFTING 0.911
SHOPLIFTING 0.909
SHOPLIFTING 0.972
SHOPLIFTING 0.883
SHOPLIFTING 0.879
SHOPLIFTING 0.749
SHOPLIFTING 0.896
SHOPLIFTING 0.671
SHOPLIFTING 0.878
SHOPLIFTING 0.898
SHOPLIFTING 0.751
SHOPLIFTING 0.777
NORMAL 0.313
SHOPLIFTING 0.975
SHOPLIFTING 0.507
NORMAL 0.397
SHOPLIFTING 0.94
SHOPLIFTING 0.987
SHOPLIFTING 0.912
SHOPLIFTING 0.946
SHOPLIFTING 0.878
SHOPLIFTING 0.82
SHOPLIFTING 0.722
SHOPLIFTING 0.61
SHOPLIFTING 0.5
SHOPLIFTING 0.719
NORMAL 0.363
SHOPLIFTING 0.668
SHOPLIFTING 0.97
SHOPLIFTING 0.942
NORMAL 0.394
SHOPLIFTING 0.999
NORMAL 0.457
NORMAL 0.38
NORMAL 0.063
NORMAL 0.15
NORMAL 0.178
NORMAL 0.423
NORMAL 0.17
NORMAL 0.123
NORMAL 0.187
SHOPLIFTING 0.543
NORMAL 0.431
SHOPLIFTING 0.986
NORMAL 0.443
NORMAL 0.317
NORMAL 0.111
SHOPLIFTING 0.799
SHOPLIFTING 0.811
NORMAL 0.483
NORMAL 0.151
SHOPLIFTING 0.674
NORMAL 0.236
NORMAL 0.063
SHOPLIFTING 0.93
SHOPLIFTING 0.76
NORMAL 0.257
NORMAL 0.346
SHOPLIFTING 0.865
SHOPLIFTING 0.912
SHOPLIFTING 0.991
SHOPLIFTING 0.845
SHOPLIFTING 0.986
SHOPLIFTING 0.999
SHOPLIFTING 0.999
SHOPLIFTING 0.995
SHOPLIFTING 0.995
SHOPLIFTING 0.99
SHOPLIFTING 1.0
SHOPLIFTING 1.0
NORMAL 0.403
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 0.549
NORMAL 0.187
SHOPLIFTING 0.788
NORMAL 0.345
SHOPLIFTING 0.998
SHOPLIFTING 0.924
NORMAL 0.42
SHOPLIFTING 0.997
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.819
SHOPLIFTING 0.986
SHOPLIFTING 0.986
SHOPLIFTING 0.927
NORMAL 0.429
SHOPLIFTING 0.987
SHOPLIFTING 0.993
SHOPLIFTING 0.96
SHOPLIFTING 0.867
SHOPLIFTING 0.859
SHOPLIFTING 0.912
SHOPLIFTING 0.878
SHOPLIFTING 0.855
SHOPLIFTING 0.977
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.998
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.997
SHOPLIFTING 0.998
SHOPLIFTING 1.0
SHOPLIFTING 0.998
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.995
SHOPLIFTING 0.998
SHOPLIFTING 0.995
SHOPLIFTING 1.0
SHOPLIFTING 0.844
NORMAL 0.417
SHOPLIFTING 0.819
SHOPLIFTING 0.999
SHOPLIFTING 0.687
NORMAL 0.005
NORMAL 0.008
NORMAL 0.041
NORMAL 0.443
NORMAL 0.155
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 0.981
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.993
NORMAL 0.389
SHOPLIFTING 0.618
SHOPLIFTING 1.0
SHOPLIFTING 0.994
SHOPLIFTING 0.991
NORMAL 0.01
SHOPLIFTING 0.648
SHOPLIFTING 0.964
NORMAL 0.199
NORMAL 0.241
SHOPLIFTING 0.96
SHOPLIFTING 0.984
SHOPLIFTING 0.999
SHOPLIFTING 0.977
SHOPLIFTING 1.0
SHOPLIFTING 0.976
SHOPLIFTING 0.995
SHOPLIFTING 0.99
SHOPLIFTING 0.991
SHOPLIFTING 0.982
SHOPLIFTING 0.986
SHOPLIFTING 0.997
SHOPLIFTING 0.985
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.998
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.991
SHOPLIFTING 0.998
SHOPLIFTING 0.999
SHOPLIFTING 0.997
SHOPLIFTING 0.992
SHOPLIFTING 0.938
SHOPLIFTING 0.941
SHOPLIFTING 0.946
NORMAL 0.112
SHOPLIFTING 0.569
SHOPLIFTING 1.0
SHOPLIFTING 0.815
SHOPLIFTING 0.68
SHOPLIFTING 0.981
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.988
SHOPLIFTING 1.0
SHOPLIFTING 0.991
SHOPLIFTING 0.927
SHOPLIFTING 0.986
SHOPLIFTING 0.987
SHOPLIFTING 1.0
SHOPLIFTING 0.99
SHOPLIFTING 0.948
SHOPLIFTING 0.999
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
NORMAL 0.497
NORMAL 0.017
SHOPLIFTING 0.982
SHOPLIFTING 0.847
SHOPLIFTING 0.992
SHOPLIFTING 0.995
SHOPLIFTING 0.993
NORMAL 0.01
SHOPLIFTING 0.648
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.966
SHOPLIFTING 0.998
SHOPLIFTING 0.978
SHOPLIFTING 1.0
SHOPLIFTING 0.997
SHOPLIFTING 0.985
SHOPLIFTING 0.911
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.98
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.98
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.994
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.993
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.998
SHOPLIFTING 0.825
SHOPLIFTING 0.965
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 0.996
SHOPLIFTING 0.996
SHOPLIFTING 0.99
SHOPLIFTING 0.995
SHOPLIFTING 0.979
SHOPLIFTING 0.898
SHOPLIFTING 0.996
SHOPLIFTING 0.9
SHOPLIFTING 0.958
SHOPLIFTING 0.888
SHOPLIFTING 0.916
SHOPLIFTING 0.944
SHOPLIFTING 1.0
SHOPLIFTING 0.988
SHOPLIFTING 0.924
SHOPLIFTING 0.831
SHOPLIFTING 0.955
SHOPLIFTING 0.889
SHOPLIFTING 0.913
SHOPLIFTING 1.0
NORMAL 0.052
NORMAL 0.347
NORMAL 0.052
NORMAL 0.296
NORMAL 0.1
SHOPLIFTING 1.0
NORMAL 0.125
NORMAL 0.09
SHOPLIFTING 0.772
NORMAL 0.179
SHOPLIFTING 0.999
SHOPLIFTING 0.999
SHOPLIFTING 0.982
SHOPLIFTING 1.0
SHOPLIFTING 1.0
SHOPLIFTING 0.999
SHOPLIFTING 0.997
SHOPLIFTING 1.0